### PR TITLE
Add cos_fuv_g140l_800.txt wavecat file

### PR DESCRIPTION
**Pull request by rendinam**

### CODE REVIEW

**Comment by pllim** [comment]
So, this is a *new* file and not replacing an existing file? Just want to make sure. What is the story behind this?

**Comment by rendinam** [comment]
This is a new file, not a replacement. Still piecing together the story. Apparently there is an additional component missing before this can be usefully merged which is an update of the `wavecat.dat` file to reflect this addition. Once that's available, I'll add it to this PR.

**Comment by pllim** [comment]
OK, I added "[WIP]" to the title of this PR. Please remove it when you think it is ready for merging. Thanks!

**Comment by pllim** [comment]
@rendinam -- Is this ready now?

**Comment by rendinam** [comment]
This is ready to merge now. I was waiting on feedback from some tests.

**Comment by pllim** [comment]
Thanks! :dancing_women:

**Pull request merged**
