### PR TITLE
Setuptools conversion

### PR DESCRIPTION
**Pull request by jhunkeler**
(I'm not sure we're touching this package to be honest... Let me know.)

### CODE REVIEW

**Comment by pllim** [comment]
Yeah, I am not sure about this one. Marshall has a software that depends on this. If I now tell him that he also needs `relic` to use this... Also, did you get blessing from the ETC team?

**Comment by jhunkeler** [comment]
I'm pretty sure they might be using (or planning to use) a standalone fork under SVN. @vglaidler may be able to confirm.

**Comment by pllim** [comment]
I think if @vglaidler says this is okay, you can go ahead. Marshall can always just fall back on the released version. We don't have big updates planned for this package.

**Comment by pllim** [comment]
@jhunkeler , so ETC does not care. This is good to merge. Are you going to do all the relevant PRs at the same time? Or you want me to merge this whenever?

**Comment by jhunkeler** [comment]
@plim I'd prefer to merge these with some degree of synchronicity. The reason is, the build system's recipes also need to be updated to reflect these merges (there's already a branch in place for this on http://github.com/astroconda/astroconda-dev).

I'd like to test some of these conversions more thoroughly too. I've been having trouble with data files not getting assimilated by `python setup.py bdist`. Or `sdist` omitting data but `bdist` including them. It's seemingly random.

**Comment by pllim** [comment]
Okay. You have the :+1: to merge when you are ready. Thanks!

**Comment by pllim** [comment]
I messed with the MANIFEST recently, so this needs another rebasing. FYI.

**Comment by pllim** [comment]
@jhunkeler -- pinging you on this. OK to merge now?

**Pull request merged**
