### PR TITLE
Adding some new tests (HETC-885)

### PR DESCRIPTION
**Pull request by isaacspitzer**
Added a couple new tests and am using this PR to test CI.  Tests were automatically kicked off when the PR was opened, and were also kicked off as I pushed new changes after the PR was already open.  Test results can be found in the "Checks" tab at the top, next to the "Files changed" tab.

### CODE REVIEW

**Comment by isaacspitzer** [comment]
I determined what tests to add by using the codecov tool, which plugs into github.
https://app.codecov.io/
You should be able to set up an account with your github credentials, then look at the pysynphot project.  It shows how much of the project is covered by your test cases, and you can look through the files and see exactly which lines are hit by test cases, and which lines/methods have no coverage.

**Review by cdsontag — APPROVED** [review]
This is all rather exciting

**Review by dchitti-stsci — APPROVED** [review]

**Review by oiintam — APPROVED** [review]
The CI feature looks very interesting and I am excited!

**Review by ariedel — APPROVED** [review]
Very interested to see what else we can do with Github CI

**Pull request merged**
