### PR TITLE
Pysynphot

### PR DESCRIPTION
**Pull request by sailender2015**
https://jira.stsci.edu/browse/SPB-686

Modify build/delivery process, distribute pysynphot (C extension) via Wheel

Modify build and delivery process so that pysynphot - C is distributed via a Wheel in pypi.

### CODE REVIEW

**Comment by pllim** [comment]
The replacements are `synphot_refactor` and `stsynphot_refactor` but you don't have to worry about those. They already have wheels.

**Comment by zanecodes** [comment]
Gotcha, thanks!

**Comment by pllim** [comment]
By the way, why is this implementation so different from https://github.com/spacetelescope/stsci.tools/blob/master/.github/workflows/publish-to-pypi.yml ?

**Comment by zanecodes** [comment]
GitHub introduced [Reusable Workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) as a public beta feature a few weeks after this PR was opened, allowing us to abstract away the individual Custom Actions into a single Reusable Workflow (see [the similar drizzlepac PR for some details](https://github.com/spacetelescope/drizzlepac/pull/1156#issuecomment-943507520)).

This PR merged very shortly after we implemented our Reusable Workflow and wasn't updated to include it, but probably should be when we have time. Due to the nature of reusable workflows, we shouldn't have to change anything in consuming repositories such as this one going forward.

**Pull request merged**
