### PR TITLE
Consolidate relic initialization

### PR DESCRIPTION
**Pull request by jhunkeler**
1. Use `pkgutil` to determine if `relic` has been installed (i.e. `pip`). If so, fall through to `import relic.release`.
2. Check whether `relic` exists and is an empty directory (90% chance it's a submodule). If so, initialize the `relic` submodule.
3. Check whether `relic` does not exist. If not, clone `relic`
4. If either the submodule initialization or clone operation succeed, insert the local `relic` directory into `sys.path`

In all cases `import relic.release` occurs only once.

### CODE REVIEW

**Comment by pllim** [comment]
Doesn't this add `git` itself as an installation dependency when someone does `pip install`? I am not sure how I feel about that.

**Comment by pllim** [comment]
Note: This is an alternative to #84 to address #83.

**Comment by jhunkeler** [comment]
If #83 handles installing `relic` as a dependency, then logic in this PR here would `import relic.release` from `site-packages` rather than the current directory and skip over the git calls completely.

**Comment by pllim** [comment]
Currently, `relic` is not a declared dependency, but a sub-module, so as-is, `git` logic would be used.

If we want to make `relic` a formal third-party dependency, then there is no longer a need to have it as a submodule. Right? Or am I confusing myself?

**Comment by jhunkeler** [comment]
The general approach when not using a submodule is to clone `relic` with `git` and use it at runtime to support `setup.py`. Pretty much every package using relic right now has `git` as an implicit dependency whether you're compiling against an sdist tarball, or pip/easy_install/pypi. 

As far I am aware, we haven't received any tickets about it causing issues in the wild.

**Comment by jhunkeler** [comment]
OK, I tested this PR against this a modified `MANIFEST.in`:
```$ cat MANIFEST.in
include README.rst
include LICENSE.md

include RELIC-INFO

recursive-include doc *
recursive-include relic *
prune relic/.git
prune relic/tests

prune build
prune doc/build

global-exclude *.pyc *.o```

The `relic` bundled with the `sdist` tarball is imported first and the logic in `setup.py` makes no calls to `git`. In any case, I believe PR still helps people that are building with `pip install git+https://...`, or cloning the repository manually and building from source.

**Comment by pllim** [comment]
Are you saying that this PR now *complements* #84 (with the expanded manifest) instead of replacing it? That is, I am to merge both this one and the other one?

**Comment by jhunkeler** [comment]
Correct... I think this PR is a decent compromise. The `sdist` bundle of `relic` will work as intended, and users cloning the repo directly will benefit from not having to do anything special to get it to compile.

**Pull request merged**
